import React, { useState } from 'react';
import { motion } from 'framer-motion';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { 
  Utensils, Sparkles, Brain, CheckCircle2, 
  AlertTriangle, Flame, Info 
} from 'lucide-react';
import { toast } from 'react-toastify';

const DietPlanner = () => {
  const { user, API_URL } = useAuth();
  const [dietPlan, setDietPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const generatePlan = async () => {
    if (!user.profile?.weight || !user.profile?.age) {
      toast.info('Please complete your health profile first!');
      return;
    }

    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await axios.post(`${API_URL}/diet/generate`, {}, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setDietPlan(res.data);
      toast.success('AI Diet Plan generated!');
    } catch (err) {
      toast.error('Failed to generate diet plan');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-12">
        <div>
          <h1 className="text-3xl font-bold heading-gradient">AI Diet Planner</h1>
          <p className="text-slate-400">Personalized nutrition plans generated by advanced AI based on your profile.</p>
        </div>
        <button 
          onClick={generatePlan}
          disabled={loading}
          className="btn-primary flex items-center gap-2 px-8 py-4 shadow-xl shadow-primary-500/20"
        >
          {loading ? (
            <div className="flex items-center gap-2">
              <div className="animate-spin rounded-full h-4 w-4 border-2 border-white/30 border-t-white"></div>
              Generating...
            </div>
          ) : (
            <>
              <Sparkles size={20} /> Generate My Plan
            </>
          )}
        </button>
      </div>

      {!dietPlan ? (
        <div className="glass-card p-12 text-center max-w-2xl mx-auto">
          <div className="w-20 h-20 bg-primary-500/10 rounded-3xl flex items-center justify-center text-primary-500 mx-auto mb-6">
            <Brain size={40} />
          </div>
          <h2 className="text-2xl font-bold mb-4">No Active Plan</h2>
          <p className="text-slate-400 mb-8">
            Our AI is ready to analyze your profile (Age: {user.profile?.age || '?'}, Weight: {user.profile?.weight || '?'}kg) 
            to create a perfect meal strategy for your {user.profile?.goal || 'health'} goal.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-left max-w-md mx-auto">
            <div className="flex items-center gap-2 text-sm text-slate-300">
              <CheckCircle2 className="text-accent" size={16} /> Personalized Macros
            </div>
            <div className="flex items-center gap-2 text-sm text-slate-300">
              <CheckCircle2 className="text-accent" size={16} /> Disease Optimization
            </div>
            <div className="flex items-center gap-2 text-sm text-slate-300">
              <CheckCircle2 className="text-accent" size={16} /> Calorie Tracking
            </div>
            <div className="flex items-center gap-2 text-sm text-slate-300">
              <CheckCircle2 className="text-accent" size={16} /> Food Exclusions
            </div>
          </div>
        </div>
      ) : (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid grid-cols-1 lg:grid-cols-3 gap-8"
        >
          {/* Main Meals */}
          <div className="lg:col-span-2 space-y-6">
            <MealCard 
              title="Breakfast" 
              data={dietPlan.breakfast} 
              icon={<Utensils className="text-orange-400" />} 
            />
            <MealCard 
              title="Lunch" 
              data={dietPlan.lunch} 
              icon={<Utensils className="text-primary-400" />} 
            />
            <MealCard 
              title="Dinner" 
              data={dietPlan.dinner} 
              icon={<Utensils className="text-secondary-400" />} 
            />
          </div>

          {/* Sidebar Insights */}
          <div className="space-y-6">
            <div className="glass-card p-6 bg-accent/5 border-accent/20">
              <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-accent">
                <Info size={20} /> Nutrition Tips
              </h3>
              <ul className="space-y-3">
                {dietPlan.tips?.map((tip, i) => (
                  <li key={i} className="text-sm text-slate-300 flex gap-2">
                    <span className="text-accent mt-1">•</span> {tip}
                  </li>
                ))}
              </ul>
            </div>

            <div className="glass-card p-6 bg-red-500/5 border-red-500/20">
              <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-red-400">
                <AlertTriangle size={20} /> Foods to Avoid
              </h3>
              <ul className="space-y-3">
                {dietPlan.avoid?.map((item, i) => (
                  <li key={i} className="text-sm text-slate-300 flex gap-2">
                    <span className="text-red-400 mt-1">•</span> {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
};

const MealCard = ({ title, data, icon }) => (
  <div className="glass-card p-6">
    <div className="flex items-center justify-between mb-6">
      <div className="flex items-center gap-3">
        {icon}
        <h3 className="text-xl font-bold">{title}</h3>
      </div>
      <div className="flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full">
        <Flame size={14} className="text-orange-500" />
        <span className="text-sm font-bold">{data.calories} kcal</span>
      </div>
    </div>
    <ul className="space-y-2">
      {data.meals?.map((meal, i) => (
        <li key={i} className="flex items-center gap-3 p-3 bg-white/5 rounded-xl border border-white/5">
          <div className="w-2 h-2 rounded-full bg-primary-500"></div>
          <span className="text-slate-200">{meal}</span>
        </li>
      ))}
    </ul>
  </div>
);

export default DietPlanner;
